### ISSUE TITLE
Overwriting new keys with old keys?

### ISSUE THREAD

**Issue by Tschipcraft** [Pitan76/CompatDatapacks#1]
Hello, a bug report has been filed over on one of my data packs not working when installed alongside MCPitanLib (https://github.com/Tschipcraft/dynamiclights/issues/49). I've done some digging around and this embedded mod seems to be causing the incompatibility.
From the looks of it, if both the old keys and the new keys are present, the old keys get loaded and replace the new keys (since the loading part of the old keys happens after the new keys are loaded)?

https://github.com/Pitan76/CompatDatapacks/blob/57d7b0d696f1fa1d6a6d57576f8850f2492f5fb5/common/src/main/java/net/pitan76/compatdatapacks/mixin/JsonDataLoaderMixin.java#L39-L42

Could you please provide more documentation or a way to opt-out (or switch to opt-in) of this behavior so that I can fix this?

**Comment by PTOM76** [comment]
thanks for your reporting!
fixed the problem.
